// actions
export const ACTIONS = {
  THROW_ERROR: 'THROW_ERROR',
  SET_CARDS: 'SET_CARDS',
  SET_INFO: 'SET_INFO',
  GET_CARDS: 'GET_CARDS',
  SHUFFLE_CARDS: 'SHUFFLE_CARDS',
  DEAL_CARDS: 'DEAL_CARDS',
  GO_BATTLE: 'GO_BATTLE',
  SET_PLAY_MODE: 'SET_PLAY_MODE',
  SET_GAME_LEVEL: 'SET_GAME_LEVEL',
  COMPUTER_TURN: 'COMPUTER_TURN'
}

// enums
export const PLAY_MODE = {
  VS_COMPUTER: 'VS_COMPUTER',
  VS_LOCAL: 'VS_LOCAL',
  VS_REMOTE: 'VS_REMOTE'
}

export const PLAYERS = {
  PLAYER_1: 'PLAYER_1',
  PLAYER_2: 'PLAYER_2'
}

export const GAME_STATE = {
  PRE_GAME: 'PRE_GAME',
  DURING_GAME: 'DURING_GAME',
  POST_GAME: 'POST_GAME'
}

export const GAME_LEVEL = {
  EASY: 'EASY',
  MEDIUM: 'MEDIUM',
  HARD: 'HARD',
  RANDOM: 'RANDOM',
  GT_MEDIAN: 'GT_MEDIAN',
  GT_AVERAGE: 'GT_AVERAGE',
  BEST_ON_CARD: 'BEST_ON_CARD'
}
