// actions
export const ACTIONS = {
  THROW_ERROR: 'THROW_ERROR',
  SET_CARDS: 'SET_CARDS',
  GET_CARDS: 'GET_CARDS',
  SHUFFLE_CARDS: 'SHUFFLE_CARDS',
  DEAL_CARDS: 'DEAL_CARDS',
  GO_BATTLE: 'GO_BATTLE',
  SET_PLAY_MODE: 'SET_PLAY_MODE',
  COMPUTER_TURN: 'COMPUTER_TURN'
}

// enums
export const PLAY_MODE = {
  VS_COMPUTER: 'VS_COMPUTER',
  VS_LOCAL: 'VS_LOCAL',
  VS_REMOTE: 'VS_REMOTE'
}

export const PLAYERS = {
  PLAYER_1: 'PLAYER_1',
  PLAYER_2: 'PLAYER_2'
}
